services:
  api-book-library:
    container_name: api-book-library
    ports:
      - "5000:5000"
    env_file: ./.env
    depends_on:
      - mysql-book-library
      - redis-book-library
    environment:
      REDIS_HOST: redis-book-library
      REDIS_PORT: 6379

  mysql-book-library:
    image: mysql:8.0
    container_name: mysql-book-library
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin-book-library:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-koleksi-buku
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-book-library
    depends_on:
      - mysql-book-library

  redis-book-library:
    image: redis:7
    container_name: redis-book-library
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data:
